/*
Given a List og strings word, determine if it is a palindrome.
Considere only alphanumeric characters and ignoring cases.


Example 1:

Input: s = "racecar"
Output: true
Explanation: "racecar" is a palindrome.


Example 2:

Input: s = "box"
Output: false
Explanation: "box" is not a palindrome. box != xob


*/

public with sharing class ValidPalindrome {

    public static Boolean isValidPalindrome(List<String> word)
    {

        return true; // or false
    }

}
